version: "3.8"

services:
  react-app:
    container_name: react-web
    build:
      context: .
      dockerfile: docker/react-web/Dockerfile
    tty: true
    volumes:
      - ./react-tutorial-with-docker-impl:/app:cached
      - react_node_modules:/app/node_modules
    ports:
      - 3000:3000

volumes:
  react_node_modules:
